### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Zagorodnyi** [charlielee/nwjs-packager#12]
since versions in from "https://nwjs.io/versions.json" come in format 'v0.45.4', there is no need to add 'v' symbol in front of version name in Downloader.js

**Comment by charlielee** [comment]
Thanks for reporting this issue will investigate.

**Comment by Richienb** [comment]
@Zagorodnyi Just change 'v0.45.4' to '0.45.4'

**Comment by charlielee** [comment]
Thanks @Richienb for making the README clearer. I suppose it could be changed so Downloader.js handles both versions starting with and without a `v`. I wouldn't want to remove the current format though as it would not be backwards compatible.
