### ISSUE TITLE
Unknown command: "nwp"

### ISSUE THREAD

**Issue by tmblog** [charlielee/nwjs-packager#28]
Hi I am probably missing something, I followed the instructions to build. When I run: `nwp` from the same directory I get `Unknown command: "nwp"` is that the full command?
What am I missing?

**Comment by charlielee** [comment]
Hi @tmblog! The issue will be that the `nwp` command isn't in your path variable.

There's a couple of ways you could get round this:

Add a line similar to the below to your  `package.json` file and you can run it with `npm run-script build`:

```
...
  scripts: {
    build: "nwp"
  }
...
```
 
Or if you install nwjs-packager as a global NPM package with `npm install -g nwjs-packager` then `nwp` should just work from a terminal window.

**Comment by tmblog** [comment]
That's great, thank you for the prompt reply.
