### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmanchhabra** [charlielee/nwjs-packager#36]
Hi @charlielee,

I've recently created a GitHub org called [NW Userland](https://github.com/nw-userland) which is my attempt to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by charlielee** [comment]
Thanks for your interest in this project. I've noticed there is a similar organisation called [nwutils](https://github.com/nwutils). Would this tool make sense to be a part of that organisation instead as it appears to be more established?

**Comment by ayushmanchhabra** [comment]
Yeah that actually makes more sense 😅

**Comment by ayushmanchhabra** [comment]
You can contact Jared [here](https://gitter.im/nwjs/nw.js) since he has admin access!

cc @TheJaredWilcurt

**Comment by TheJaredWilcurt** [comment]
Hey, I've invited you to NW-Utils organization. If you accept and move your repo there I'll add you as an admin to it, so nothing changes, it just gets grouped with rest of the community projects and easier for people to find.

**Comment by charlielee** [comment]
I've transferred the repo over. I hope this project can be useful to the community!

**Comment by TheJaredWilcurt** [comment]
cool, set you as admin again
